
#! LARGE FLOOR PRICE
#? FROM OPENSEA API > CHECK BY TASKS API CALL

#! LOW GAS DETECTED
#? https://etherscan.io/gastracker [CAN BE FETCHED FROM THE ETHERSCAN EITHER BY API OR ANYTHING ELSE]

#! TWITTER FOLLOWS
#? MAKE A COMMAND TO ADD USER PROFILE ID AND MAYBE WHEN HE/SHE FOLLOWS SEND ALERT? [WE'LL SEE WHAT TO USE HERE]

#! TRADE TRACKER
#? FROM OPENSEA API > SALES > TRANSFER

#! MINT TRACKER [WHEN LARGE MINTS OR WHEN AN ACCOUNT MINTS]
#? [need to search the API]

#! LISTING TRACKER [are two]
#? FROM OPENSEA API > LISTINGS

#! stats COMMAND
#? sends profile stats
